name: workflow

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: install Cowsay Program
        run: sudo apt-get install cowsay -y
      - name: execute cowsay command
        run: cowsay -f dragon "Welcome to GitHub Actions! dragon" >> dragon.txt
      - name: Upload Dragon file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt
        
  test_job_2:
    runs-on: ubuntu-latest
    needs: build_job_1
    steps:
    - name: Download Dragon file as artifact
      uses: actions/download-artifact@v4
      with:
        name: dragon-text-file
    - name: test file exists
      run: grep -i "dragon" dragon.txt
         
  deblopy_job_3:
    runs-on: ubuntu-latest
    needs: test_job_2
    steps:
    - name: Download Dragon file as artifact
      uses: actions/download-artifact@v4
      with:
        name: dragon-text-file
    - name: Read Dragon file
      run: cat dragon.txt
        
