name: workflow

on: push

jobs:
  currentjob:
    runs-on: ubuntu:latest
    steps:
      - name: Welcome message
        run: echo "welcomeee gh"
      - name: List files
        run: ls

      - name: Read README.md
        run: cat README.md