name: workflow

on: push

jobs:
  currentjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Welcome message
        run: echo "welcomeee gh"
      - name: List files
        run: ls

      - name: Read README.md
        run: cat README.md